In [33]:
import torch

### torch.cat()

In [34]:
# Concatenate two tensors along dimension 0
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y))
print(z, z.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])


In [35]:
# Concatenate two tensors along dimension 1
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y), dim=1)
print(z, z.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


### torch.stack()

#### cat() vs stack()
- stack() creates a new dimension, but cat() doesn't.

In [36]:
# Stack two tensors along dimension 0
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = torch.stack((x, y))
print(z, z.shape)

# Stack two tensors along dimension 1
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = torch.stack((x, y), dim=1)

# Stack three tensors along dimension 0
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = torch.tensor([5, 6])
z = torch.stack((x, y, z))
print(z, z.shape)

# Stack three tensors along dimension 1
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = torch.tensor([5, 6])
z = torch.stack((x, y, z), dim=1)
print(z, z.shape)


tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])
tensor([[1, 3, 5],
        [2, 4, 6]]) torch.Size([2, 3])


### torch.chunk()

In [37]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
chunks = torch.chunk(x, 2, dim=0)

for chunk in chunks:
    print(chunk, chunk.size())

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])


In [38]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
chunks = torch.chunk(x, 3, dim=1)

for chunk in chunks:
    print(chunk, chunk.shape)

tensor([[ 1],
        [ 4],
        [ 7],
        [10]]) torch.Size([4, 1])
tensor([[ 2],
        [ 5],
        [ 8],
        [11]]) torch.Size([4, 1])
tensor([[ 3],
        [ 6],
        [ 9],
        [12]]) torch.Size([4, 1])


### torch.split()

#### chunk() vs split()
- chunk(): Splits a tensor into **N chunks**.
- split(): Splits a tensor into chunks that has **N elememts** equally.

In [39]:
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Split the tensor into three equal parts
result = torch.split(x, 3)
print(result)
print()

# Split the tensor into three parts of unequal sizes
result = torch.split(x, [4, 3, 5])
print(result)
print()
result = torch.split(x, [3, 6, 3])
print(result)
print()

x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = torch.split(x, 3, dim=1)
print(result)
print()

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
result = torch.split(x, [2, 1, 2], dim=0)
print(result)
print()

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]), tensor([10, 11, 12]))

(tensor([1, 2, 3, 4]), tensor([5, 6, 7]), tensor([ 8,  9, 10, 11, 12]))

(tensor([1, 2, 3]), tensor([4, 5, 6, 7, 8, 9]), tensor([10, 11, 12]))

(tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]]), tensor([[ 4],
        [ 8],
        [12]]))

(tensor([[1, 2, 3],
        [4, 5, 6]]), tensor([[7, 8, 9]]), tensor([[10, 11, 12],
        [13, 14, 15]]))



### torch.gather()

In [40]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Create a tensor of indices
indices = torch.tensor([[0, 1], [1, 0]])

# Gather elements from the first dimension
result = torch.gather(x, 0, indices)
print(result)

# Gather elements from the second dimension
result = torch.gather(x, 1, indices)
print(result)


tensor([[1, 5],
        [4, 2]])
tensor([[1, 2],
        [5, 4]])


In [41]:
# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a list of indices
indices = torch.tensor([[0, 2, 1], [1, 2, 0]])

# Gather elements from the tensor based on the indices
y = torch.gather(x, 1, indices)

# Print the result
print(y)

tensor([[1, 3, 2],
        [5, 6, 4]])


### torch.index_select()

In [42]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select rows with indices 0 and 2
result = torch.index_select(x, 0, torch.tensor([0, 2]))
print(result)
print()

# Select columns with indices 0 and 2
result = torch.index_select(x, 1, torch.tensor([0, 2]))
print(result)
print()

# Create a 3D tensor
x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Select the first element from each sub-tensor
result = torch.index_select(x, 0, torch.tensor([0]))
print(result)
print()

# Select the second element from each sub-tensor
result = torch.index_select(x, 1, torch.tensor([1]))
print(result)
print()

# Select the third element from each sub-tensor
result = torch.index_select(x, 2, torch.tensor([2]))
print(result)
print()


tensor([[1, 2, 3],
        [7, 8, 9]])

tensor([[1, 3],
        [4, 6],
        [7, 9]])

tensor([[[1, 2, 3],
         [4, 5, 6]]])

tensor([[[ 4,  5,  6]],

        [[10, 11, 12]]])

tensor([[[ 3],
         [ 6]],

        [[ 9],
         [12]]])



### torch.masked_select()

In [43]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a mask
mask = torch.tensor([[True, False, True], [False, True, False], [True, False, True]])

# Select elements where the mask is True
result = torch.masked_select(x, mask)
print(result)

# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a mask
mask = torch.tensor([[True, False, False], [False, True, False], [False, False, True]])

# Select elements where the mask is True
result = torch.masked_select(x, mask)
print(result)


tensor([1, 3, 5, 7, 9])
tensor([1, 5, 9])


### torch.narrow()

In [44]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Narrow the tensor to the first row
# (Tensor input, int dim, Tensor start, int length)
# (Tensor input, int dim, int start, int length)
result = torch.narrow(x, 0, 0, 1)
print(result)
print()

# Narrow the tensor to the second column
result = torch.narrow(x, 1, 1, 1)
print(result)
print()

# Narrow the tensor to the last two rows and the first two columns
result = torch.narrow(x, 0, 1, 2)
result = torch.narrow(result, 1, 0, 2)
print(result)
print()

# Narrow the tensor to the first two rows and the last column
result = torch.narrow(x, 0, 0, 2)
result = torch.narrow(result, 1, 2, 1)
print(result)


tensor([[1, 2, 3]])

tensor([[2],
        [5],
        [8]])

tensor([[4, 5],
        [7, 8]])

tensor([[3],
        [6]])


### torch.nonzero()

In [45]:
x = torch.tensor([[1, 2, 3], [4, 0, 5], [0, 6, 0]])

# Find the indices of non-zero elements
indices = torch.nonzero(x)
# Print the indices
print(indices)
print()

indices = torch.nonzero(x, as_tuple=True)
print(indices)
print()

# Find the indices of non-zero elements in the second dimension
indices = torch.nonzero(x, as_tuple=True)[1]

# Print the indices
print(indices)
print()

# Find the indices of non-zero elements in the first dimension
indices = torch.nonzero(x, as_tuple=True)[0]
# Print the indices
print(indices)
print()

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [1, 0],
        [1, 2],
        [2, 1]])

(tensor([0, 0, 0, 1, 1, 2]), tensor([0, 1, 2, 0, 2, 1]))

tensor([0, 1, 2, 0, 2, 1])

tensor([0, 0, 0, 1, 1, 2])



### torch.reshape()

- But, Use `view()` instead of `reshape()` for reshaping tensors in most cases.
- Using reshape() may cause the tensor to be copied, depending on its layout in memory. view() ensures that it will not be copied.
- `view()` ensures that the tensor is contiguous.

In [46]:
x = torch.tensor([1, 2, 3, 4, 5, 6])

# Reshape the tensor to a 2x3 matrix
y = x.reshape(2, 3)
print(y)
print()

# Reshape the tensor to a 3x2 matrix
y = x.reshape(3, 2)
print(y)
print()

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])



### torch.squeeze()

In [47]:
x = torch.tensor([[[[1, 2, 3], [4, 5, 6]]]])
print(x.size())
print()

# Squeeze the tensor to remove all single dimensions
y = torch.squeeze(x)
print(y.size())
print()

# Squeeze the tensor to remove the first dimension
y = torch.squeeze(x, dim=0)
print(y.size())
print()

# Squeeze the tensor to remove the second dimension
y = torch.squeeze(x, dim=1)
print(y.size())
print()

# Squeeze the tensor to remove the third dimension
y = torch.squeeze(x, dim=2)
print(y.size())
print()

# Create a tensor
x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(x.size())
print()

# Squeeze the tensor to remove the first dimension
y = torch.squeeze(x, dim=0)
print(y.size())
print()

# Squeeze the tensor to remove the second dimension
y = torch.squeeze(x, dim=1)
print(y.size())
print()

torch.Size([1, 1, 2, 3])

torch.Size([2, 3])

torch.Size([1, 2, 3])

torch.Size([1, 2, 3])

torch.Size([1, 1, 2, 3])

torch.Size([2, 2, 3])

torch.Size([2, 2, 3])

torch.Size([2, 2, 3])



### torch.unsqueeze()

In [48]:
x = torch.tensor([1, 2, 3])
print(x.size())
print()

# Unsqueeze the tensor to add a new dimension at the beginning
y = torch.unsqueeze(x, 0)
print(y.size())
print()

# Unsqueeze the tensor to add a new dimension at the end
y = torch.unsqueeze(x, -1)
print(y.size())
print()

# Unsqueeze the tensor to add a new dimension at the second position
y = torch.unsqueeze(x, 1)
print(y.size())
print()

# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size())
print()

# Unsqueeze the tensor to add a new dimension at the beginning
y = torch.unsqueeze(x, 0)
print(y.size())
print()

# Unsqueeze the tensor to add a new dimension at the end
y = torch.unsqueeze(x, -1)
print(y.size())
print()

# Unsqueeze the tensor to add a new dimension at the second position
y = torch.unsqueeze(x, 1)
print(y.size())
print()

# Create a tensor
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(x.size())
print()

# Unsqueeze the tensor to add a new dimension at the beginning
y = torch.unsqueeze(x, 0)
print(y.size())
print()

# Unsqueeze the tensor to add a new dimension at the end
y = torch.unsqueeze(x, -1)
print(y.size())
print()

# Unsqueeze the tensor to add a new dimension at the second position
y = torch.unsqueeze(x, 1)
print(y.size())
print()

torch.Size([3])

torch.Size([1, 3])

torch.Size([3, 1])

torch.Size([3, 1])

torch.Size([2, 3])

torch.Size([1, 2, 3])

torch.Size([2, 3, 1])

torch.Size([2, 1, 3])

torch.Size([12])

torch.Size([1, 12])

torch.Size([12, 1])

torch.Size([12, 1])



### torch.t()

- `X.T` or `x.t()` is for 1D or 2D.

In [49]:
# prompt: show the examples of torch.t()

x = torch.tensor([[1, 2, 3]])
y = torch.t(x)
print(y)

x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.t(x)
print(y)


tensor([[1],
        [2],
        [3]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### torch.transpose()

- It's for 3D or more.

In [50]:
x = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(x.size())
print()

# Transpose the tensor along the first and second dimensions
y = torch.transpose(x, 0, 1)
print(y, y.size())
print()

# Transpose the tensor along the first and third dimensions
y = torch.transpose(x, 0, 2)
print(y, y.size())
print()

# Transpose the tensor along the second and third dimensions
y = torch.transpose(x, 1, 2)
print(y, y.size())
print()

torch.Size([2, 2, 3])

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]]) torch.Size([2, 2, 3])

tensor([[[ 1,  7],
         [ 4, 10]],

        [[ 2,  8],
         [ 5, 11]],

        [[ 3,  9],
         [ 6, 12]]]) torch.Size([3, 2, 2])

tensor([[[ 1,  4],
         [ 2,  5],
         [ 3,  6]],

        [[ 7, 10],
         [ 8, 11],
         [ 9, 12]]]) torch.Size([2, 3, 2])



### torch.take()

- Returns a tensor at specified indices when slicing is not continuous.

In [51]:
# Define a 2D input tensor
input_tensor = torch.tensor([[1, 2], [3, 4]])

# Indices of elements to take
indices = torch.tensor([0, 2])

# Use torch.take() to select elements
selected_elements = torch.take(input_tensor, indices)

print("Input Tensor:\n", input_tensor)
print("Selected Elements:", selected_elements)

Input Tensor:
 tensor([[1, 2],
        [3, 4]])
Selected Elements: tensor([1, 3])


### torch.unbind()

- Removes a tensor dimension by returning a tuple of the removed dimension.

In [52]:
# Define a 3D input tensor
input_tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Unbind the tensor along dimension 0
tensors_tuple = torch.unbind(input_tensor, dim=0)

print("Input Tensor:\n", input_tensor)
print("\nUnbound Tensors:")
for i, t in enumerate(tensors_tuple):
    print(f"Tensor {i}:\n", t)


Input Tensor:
 tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

Unbound Tensors:
Tensor 0:
 tensor([[1, 2],
        [3, 4]])
Tensor 1:
 tensor([[5, 6],
        [7, 8]])
Tensor 2:
 tensor([[ 9, 10],
        [11, 12]])


### torch.where()

In [53]:
# Define the condition tensor
condition = torch.tensor([[True, False], [False, True]])

# Define tensors x and y
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

# Apply torch.where()
result = torch.where(condition, x, y)

print("Result:\n", result)

Result:
 tensor([[1, 6],
        [7, 4]])


PyTorch is so Pythonic in nature that like most Python classes, some PyTorch functions can be applied directly on a tensor using a built-in method such as x..size().