In [2]:
import torch

### torch.cat()

In [10]:
# Concatenate two tensors along dimension 0
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y))
print(z, z.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) torch.Size([4, 2])


In [11]:
# Concatenate two tensors along dimension 1
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])
z = torch.cat((x, y), dim=1)
print(z, z.shape)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) torch.Size([2, 4])


### torch.chunk()

In [26]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
chunks = torch.chunk(x, 2, dim=0)

for chunk in chunks:
    print(chunk, chunk.size())

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[ 7,  8,  9],
        [10, 11, 12]]) torch.Size([2, 3])


In [29]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
chunks = torch.chunk(x, 3, dim=1)

for chunk in chunks:
    print(chunk, chunk.shape)

tensor([[ 1],
        [ 4],
        [ 7],
        [10]]) torch.Size([4, 1])
tensor([[ 2],
        [ 5],
        [ 8],
        [11]]) torch.Size([4, 1])
tensor([[ 3],
        [ 6],
        [ 9],
        [12]]) torch.Size([4, 1])
